apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libcalproxy.fullname" . }}
  labels:
    {{- include "libcalproxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "libcalproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "libcalproxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "libcalproxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.libcalproxy.env .Values.libcalproxy.envSecrets }}
          env:
            {{- if .Values.libcalproxy.env }}
            {{- range $k, $v := .Values.libcalproxy.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.libcalproxy.envSecrets }}
            {{- range $k, $v := .Values.libcalproxy.envSecrets }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ $v }}
                  key: {{ $k | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.libcalproxy.env.HTTP_PORT | default 8888 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: {{ .Values.libcalproxy.env.HTTP_PORT | default 8888 }}
          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.libcalproxy.env.HTTP_PORT | default 8888 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
