openapi: "3.0.0"
info:
  version: 1.0.0
  title: LibCal-Proxy API
  license:
    name: The 3-Clause BSD License
servers:
  - url: http://github.com/uclalibrary/libcal-proxy
paths:
  /status:
    get:
      summary: Get Application Status
      description: "A response indicating the current status of the application. This may include information about the
      health of the server, details about which configuration options are engaged, and other things."
      operationId: getStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '500':
          description: There was an internal server error
  /libcal/{theQuery}:
    get:
      summary: Get LibCal API Output
      description: "JSON Output from LibCal APIs"
      operationId: getProxy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
        '400':
          description: Bad request from client
        '500':
          description: There was an internal server error
