name: Maven PR Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - name: Check out code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142 # v3.3.0
        with:
          cache: maven
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "clean compile javadoc:javadoc verify"
          maven_profiles: default
          maven_args: >
            -V -ntp -Ddocker.showLogs=true
            -Dlibcal.client1.id=${{ secrets.LIBCAL_CLIENT1_ID }}
            -Dlibcal.client1.secret=${{ secrets.LIBCAL_CLIENT1_SECRET }}
            -Dlibcal.client2.id=${{ secrets.LIBCAL_CLIENT2_ID }}
            -Dlibcal.client2.secret=${{ secrets.LIBCAL_CLIENT2_SECRET }}
            -Dlibcal.token.endpoint="https://calendar.library.ucla.edu/1.1/oauth/token"
            -Dlibcal.base.url="https://calendar.library.ucla.edu"
            -Dlibcal.allowed.ips="127.0.0.0/16,10.10.10.0/27"
      - name: Detect New Helm Chart
        run: |
          CURRENT_CHART_VERSION=$(cat pom.xml | grep -i '<libcal.helm.chart.version>' | xargs | grep -oPm1 "(?<=<libcal.helm.chart.version>)[^<]+")
          HTTP_RESP=$(curl -s -w "%{http_code}" -o /dev/null https://chartmuseum.library.ucla.edu/api/charts/libcalproxy/${CURRENT_CHART_VERSION})
          echo "CM_HTTP_RESP=${HTTP_RESP}" >> $GITHUB_ENV
          echo "CURRENT_CHART_VERSION=${HTTP_RESP}" >> $GITHUB_ENV
      - name: Detect New Helm Chart
        run: |
          find target/helm
      - name: Deploy Helm Chart
        if: env.CM_HTTP_RESP == 404
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "com.deviceinsight.helm:helm-maven-plugin:2.10.0:deploy"
          maven_profiles: default
          maven_args: >
            -Drevision=${{ env.CURRENT_CHART_VERSION }}
            -Dhelm.maven.repo.publish.url=${{ secrets.UCLALIB_HELM_CM_PUBLISH_URL }}
            -Dhelm.maven.repo.username=${{ secrets.UCLALIB_HELM_CM_USERNAME }}
            -Dhelm.maven.repo.password=${{ secrets.UCLALIB_HELM_CM_PASSWORD }}
